'''Input: List of ground truth test images, 
		  directory containing test gt images,
		  directiry containing predicted images,
		  List of images generated by corresponding predicted expression(optional),
		  number of samples that need to be displayed(optional, default=240),
		  visualization tree on/off(optional, default=off)

	Output: html file that displays gt, predicted pairs
'''
import os, sys
import numpy as np
import math
numtables = 6

def genhtml(gtlist, gtdir, preddir, predlist=None, numexs=240, vistree=False):
	if predlist == None:
		predlist = gtlist
	assert len(predlist) == len(gtlist)
	randind = np.random.permutation(range(len(gtlist)))[:numexs]
	filepath = os.path.dirname(preddir)+'/results.html'
	fp = open(filepath, 'w')
	fp.write('''
			<!DOCTYPE html>
			<html lang="en">
			<head>
			<meta charset="UTF-8">
			<title>Randomly Sampled Examples</title>
			</head>
			<body>
			''')
	exspertable = math.ceil(numexs/numtables)
	
	for i in range(numtables):
		fp.write('''
			<table width="200" border="5" style="float:left;">
			<tr>
			<th>GROUND TRUTH</th>
			<th>PREDICTED IMAGE</th>
			</tr>
			''')
		for j in range(i*exspertable, min((i+1)*exspertable, numexs)):
			fp.write('''
				<tr>
				<td> <img src=''' + gtdir + '/' + gtlist[randind[j]]+ ' alt='+ gtlist[randind[j]]+ ' height="142" width="142"> </td>'
				+'<td> <img src=' + preddir+'/'+predlist[randind[j]]+ ' alt='+ predlist[randind[j]]+ ''' height="142" width="142"> </td>
				</tr>''')


if __name__ == '__main__':
	gtdir = "/home/rishabh/Documents/experiment/3step/test"
	preddir = "/home/rishabh/Documents/experiment/3step/train"
	fp = open("/home/rishabh/Documents/experiment/3step/result.txt", 'r')
	gtlist = []
	predlist = []
	for line in fp:
		temp = line.strip('\n').split(', ')
		gtlist.append(temp[0])
		predlist.append(temp[1])
	genhtml(gtlist, gtdir, preddir, predlist=predlist)
